/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Home Assistant Developer Docs",
  "tagline": "All you need to start developing",
  "url": "https://developers.home-assistant.io",
  "baseUrl": "/",
  "favicon": "img/favicon.png",
  "organizationName": "home-assistant",
  "projectName": "developers.home-assistant",
  "themeConfig": {
    "navbar": {
      "title": "Developers",
      "logo": {
        "alt": "Home Assistant",
        "src": "img/logo.svg",
        "srcDark": "img/logo.svg"
      },
      "items": [
        {
          "label": "Home Assistant",
          "position": "left",
          "items": [
            {
              "label": "Overview",
              "to": "docs/architecture_index"
            },
            {
              "label": "Core",
              "to": "docs/development_index"
            },
            {
              "to": "docs/frontend",
              "label": "Frontend"
            },
            {
              "to": "docs/supervisor",
              "label": "Supervisor"
            },
            {
              "to": "docs/add-ons",
              "label": "Add-ons"
            },
            {
              "to": "docs/operating-system",
              "label": "Operating System"
            },
            {
              "to": "docs/voice/overview",
              "label": "Voice"
            },
            {
              "to": "docs/translations",
              "label": "Translations"
            }
          ]
        },
        {
          "to": "docs/misc",
          "label": "Misc",
          "position": "left"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "logo": {
        "alt": "Home Assistant",
        "src": "img/logo-white.svg",
        "height": "30px",
        "href": "https://www.home-assistant.io"
      },
      "style": "dark",
      "links": [
        {
          "title": "More Home Assistant",
          "items": [
            {
              "label": "Homepage",
              "href": "https://www.home-assistant.io"
            },
            {
              "label": "Data Science Portal",
              "href": "https://data.home-assistant.io"
            },
            {
              "label": "Alerts",
              "href": "https://alerts.home-assistant.io"
            },
            {
              "label": "System Status",
              "href": "https://status.home-assistant.io/"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "Blog",
              "to": "blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/home-assistant"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/hass_devs"
            },
            {
              "label": "Discord chat",
              "href": "https://www.home-assistant.io/join-chat"
            }
          ]
        },
        {
          "title": "Other",
          "items": [
            {
              "label": "Privacy",
              "href": "https://www.home-assistant.io/privacy/"
            },
            {
              "label": "Security",
              "href": "https://www.home-assistant.io/security/"
            }
          ]
        },
        {
          "title": "Thanks",
          "items": [
            {
              "html": "\n              <a href=\"https://www.netlify.com\" target=\"_blank\" rel=\"noreferrer noopener\" aria-label=\"Deploys by Netlify\">\n                <img src=\"https://www.netlify.com/v3/img/components/netlify-color-accent.svg\" alt=\"Deploys by Netlify\" />\n              </a>\n              "
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Home Assistant. Built with Docusaurus."
    },
    "image": "img/default-social.png",
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "forest"
      },
      "options": {}
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/martinpark/homeassistant-app/sidebars.js",
          "editUrl": "https://github.com/home-assistant/developers.home-assistant/edit/master/",
          "showLastUpdateTime": true
        },
        "theme": {
          "customCss": "/Users/martinpark/homeassistant-app/src/css/custom.css"
        },
        "blog": {
          "postsPerPage": 10,
          "feedOptions": {
            "type": "all"
          }
        },
        "googleAnalytics": {
          "trackingID": "UA-57927901-3"
        }
      }
    ]
  ],
  "plugins": [
    [
      "/Users/martinpark/homeassistant-app/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexDocs": true,
        "indexBlog": true,
        "highlightSearchTermsOnTargetPage": true
      }
    ]
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "warn",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
